
/* SQL script to drop all tables in the COMPANY schema. */

DROP TABLE ACCIDENT_REPORT;
DROP TABLE ADDITIONAL_PACKAGES;
DROP TABLE ORDERS_FROM;
DROP TABLE RECEIVES;
DROP TABLE REVIEW;
DROP TABLE MONTHLY_PAYMENT;
DROP TABLE SERV;
DROP TABLE SERVICE_TYPE;
DROP TABLE LOAN;
DROP TABLE MANUFACTURER;
DROP TABLE MANUFACTURING_ORDER;
DROP TABLE WARRANTY;
DROP TABLE DEALERSHIP;
DROP TABLE SALE;
DROP TABLE CAR;
DROP TABLE CAR_MODEL;
DROP TABLE CUSTOMER;
DROP TABLE STAFF;
DROP TABLE LOC;